services:
  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # O Docker vai procurar o Dockerfile aqui dentro
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: projetoDAI
    environment:
      POSTGRES_DB: projetoDAI
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: