spring.application.name=projeto
spring.datasource.url=jdbc:postgresql://192.168.233.121:5432/tub_pgu
spring.datasource.username=postgres
spring.datasource.password=igolina
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
server.port=8080