spring.application.name=projeto
spring.datasource.url=jdbc:postgresql://192.168.233.121:5432/tub_pgu
spring.datasource.username=postgres
spring.datasource.password=igolina
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
server.address=0.0.0.0
# Auth0 Management API Configuration
auth0.management.domain=tub-projeto.eu.auth0.com
auth0.management.clientId=JN2fEYIR05XTiCO2PFwNlRIajQVxkvld
auth0.management.clientSecret=EktZa9NyFi6pD_6DHBaEN_rDbYJNuou92vDe1t5JRZ1-7gSHagONtYc9uZ4yByIx
auth0.management.audience=https://tub-projeto.eu.auth0.com/api/v2/
